version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: theatre_backend
    ports:
      - "3000:3000"

  frontend:
    image: nginx:alpine
    container_name: theatre_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./public:/usr/share/nginx/html/public
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"